spring:
  datasource:
    url: jdbc:mysql://localhost/project_volunteer?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
roles:
  roleVolunteer:
    role: "ROLE_VOLUNTEER"
  roleIndividual:
    role: "ROLE_INDIVIDUAL"
  roleCompany:
    role: "ROLE_COMPANY"
